### ISSUE TITLE
Kaleido TS Cleanup

### ISSUE THREAD

**Issue by mabby-nyaa** [Kaleido-subs/Joshiraku#12]
Light QC but should probably check all signs again.

- [ ] Bleed-through on Happy New Year TS

![link](https://i.imgur.com/Bv9ZQue.png)

**Comment by mabby-nyaa** [comment]
@Angrevol Not to be overly nitpicking but there's still bleed above the e.

![link](https://i.imgur.com/yXVloP5.png)

**Comment by Angrevol** [comment]
Woops, on it. Thanks!

**Comment by mabby-nyaa** [comment]
It still exists in a couple places and could probably improve some of the splotchiness in the blending, but definitely better than before. At least it doesn't clip into the line art now, add random grey coloring, or be blatantly visible (no zooming).

![link](https://i.imgur.com/9dbEcQR.png)
https://i.imgur.com/9dbEcQR.png

![link2](https://i.imgur.com/sprikv7.png)
https://i.imgur.com/sprikv7.png

**Comment by Angrevol** [comment]
So far these have mostly been lazy patchwork fixes due to being busy with other projects.
For a clean improvement I'd probably just redo the whole mask.
Might happen but definitely low priority right now.
Thanks for the feedback. 👍
